# https://github.com/docker-library/postgres/issues/435
volumes:
  postgres_local:

services:

  postgres:
    image: postgres:15
    container_name: postgres-langaroo
    environment:
      POSTGRES_DB: langaroo
      POSTGRES_USER: lanadmin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_local:/var/lib/postgresql/data
      - ./.infrastructure/postgres/init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
